jQuery.ajax({type:"POST",url:"/wp-admin/admin-ajax.php",data:{action:"jquery_vars_APL"},dataType:"json",success:function(jQueryVars){function APL_check_ignore(e){for(var r in APL_ignore_list)if(e.indexOf(APL_ignore_list[r])>=0)return!1
return!0}function APL_loadPageInit(){jQuery("a").on("click",function(e){this.href.indexOf(APL_site_url)>=0&&1==APL_check_ignore(this.href)&&!jQuery(this).hasClass(APL_ignore_class)&&(e.preventDefault(),APL_loadPage(this.href))}),APL_search_disabled||jQuery(APL_search_class).each(function(){jQuery(this).attr("action")&&(APL_searchPath=jQuery(this).attr("action"),jQuery(this).on("submit",function(e){APL_loadPage(APL_searchPath,0,jQuery(this).serialize()),jQuery(APL_search_class+" input[type=text],"+APL_search_class+" input[type=search]").val(""),e.preventDefault()}))}),APL_comments_disabled||jQuery(APL_comments_form_class).on("submit",function(e){var data=jQuery(APL_comments_form_class).serialize()
jQuery.ajax({type:"post",url:APL_comments_form_url,data:data,dataType:"json",xhr:function(){var xhr=new window.XMLHttpRequest
return APL_comments_xhr&&eval(APL_comments_xhr),xhr},complete:function(data){APL_comments_complete&&eval(APL_comments_complete),"true"==APL_comments_reload&&APL_loadPage(""+document.location,0)}}),e.preventDefault()}),APL_login_disabled||(jQuery(APL_login_form_id).on("submit",function(e){var data=jQuery(APL_login_form_id).serialize()
jQuery.ajax({type:"POST",url:APL_login_url,data:data,xhr:function(){var xhr=new window.XMLHttpRequest
return APL_login_xhr&&eval(APL_login_xhr),xhr},complete:function(data){APL_login_complete&&eval(APL_login_complete),"true"==APL_login_reload&&APL_loadPage(""+document.location,0)}}),e.preventDefault()}),jQuery(APL_login_lost_password_form_id).on("submit",function(e){var data=jQuery(APL_login_lost_password_form_id).serialize()
jQuery.ajax({type:"POST",url:APL_login_lost_password_url,data:data,xhr:function(){var xhr=new window.XMLHttpRequest
return APL_login_lost_password_xhr&&eval(APL_login_lost_password_xhr),xhr},complete:function(data){APL_login_lost_password_complete&&eval(APL_login_lost_password_complete),"true"==APL_login_lost_password_reload&&APL_loadPage(""+document.location,0)}}),e.preventDefault()}),jQuery(APL_login_reset_password_form_id).on("submit",function(e){var data=jQuery(APL_login_reset_password_form_id).serialize()
jQuery.ajax({type:"POST",url:APL_login_reset_password_url,data:data,xhr:function(){var xhr=new window.XMLHttpRequest
return APL_login_reset_password_xhr&&eval(APL_login_reset_password_xhr),xhr},complete:function(data){APL_login_reset_password_complete&&eval(APL_login_reset_password_complete),"true"==APL_login_reset_password_reload&&APL_loadPage(""+document.location,0)}}),e.preventDefault()}),jQuery(APL_login_register_form_id).on("submit",function(e){var data=jQuery(APL_login_register_form_id).serialize()
jQuery.ajax({type:"POST",url:APL_login_register_url,data:data,xhr:function(){var xhr=new window.XMLHttpRequest
return APL_login_register_xhr&&eval(APL_login_register_xhr),xhr},complete:function(data){APL_login_register_complete&&eval(APL_login_register_complete),"true"==APL_login_register_reload&&APL_loadPage(""+document.location,0)}}),e.preventDefault()}))}function APL_loadPage(url,push,search_query){APL_isLoad||(APL_isLoad=!0,APL_started=!1,pathIndex=url.indexOf(url.split(document.domain).slice(1)),path=url.substring(pathIndex),search_query&&(path+=search_query),1!=push&&"function"==typeof window.history.pushState&&(stateObj={rand:1e3+1001*Math.random()},history.pushState(stateObj,"AJAX Loaded Content",path)),APL_before_ajax&&eval(APL_before_ajax),jQuery.ajax({type:"GET",url:url,data:search_query,cache:!1,dataType:"html",xhr:function(){var xhr=new window.XMLHttpRequest
return APL_xhr&&eval(APL_xhr),xhr},complete:function(data){APL_isLoad=!1,APL_started=!0,jQuery(document).attr("title",jQuery(data.responseText).filter("title").text()),jQuery(APL_content_id).html(jQuery(data.responseText).filter(APL_content_id).html()),APL_complete&&eval(APL_complete),APL_loadPageInit()}}))}var APL_content_id="#"+jQueryVars[0],APL_search_class="."+jQueryVars[1],APL_search_disabled=jQueryVars[2],APL_ignore_class=jQueryVars[3],APL_ignore_list=jQueryVars[4].split(", "),APL_page_load=jQueryVars[5],APL_before_ajax=jQueryVars[6],APL_xhr=jQueryVars[7],APL_complete=jQueryVars[8],APL_comments_disabled=jQueryVars[9],APL_comments_form_class="."+jQueryVars[10],APL_comments_form_url=jQueryVars[11],APL_comments_xhr=jQueryVars[12],APL_comments_complete=jQueryVars[13],APL_comments_reload=jQueryVars[14],APL_login_disabled=jQueryVars[15],APL_login_form_id="#"+jQueryVars[16],APL_login_url=jQueryVars[17],APL_login_xhr=jQueryVars[18],APL_login_complete=jQueryVars[19],APL_login_reload=jQueryVars[20],APL_login_lost_password_form_id="#"+jQueryVars[21],APL_login_lost_password_url=jQueryVars[22],APL_login_lost_password_xhr=jQueryVars[23],APL_login_lost_password_complete=jQueryVars[24],APL_login_lost_password_reload=jQueryVars[25],APL_login_reset_password_form_id="#"+jQueryVars[26],APL_login_reset_password_url=jQueryVars[27],APL_login_reset_password_xhr=jQueryVars[28],APL_login_reset_password_complete=jQueryVars[29],APL_login_reset_password_reload=jQueryVars[30],APL_login_register_form_id="#"+jQueryVars[31],APL_login_register_url=jQueryVars[32],APL_login_register_xhr=jQueryVars[33],APL_login_register_complete=jQueryVars[34],APL_login_register_reload=jQueryVars[35],APL_site_url=jQueryVars[36],APL_isLoad=!1,APL_started=!1
APL_ignore_class||(APL_ignore_class=!0),jQuery(document).ready(function(){APL_page_load&&eval(APL_page_load),APL_loadPageInit()}),window.onpopstate=function(){if(APL_started===!0){var e=""+document.location,r=e.substr(e.lastIndexOf("/")+1)
1==/s=/.test(r)?(e=e.replace(r,""),APL_loadPage(e,1,r)):APL_loadPage(e,1)}}}})
